### ISSUE TITLE
Please lock flutter version in pubspeck

### ISSUE THREAD

**Issue by vasilich6107** [bizz84/layout-demo-flutter#14]
Hi. Trying to run the project but it does not work with latest flutter stable
Could you lock the version number so we can know what version to use via `fvm`

**Comment by vasilich6107** [comment]
was able to run on `2.0.3`

**Comment by bizz84** [comment]
Project requires Dart 3.2 (Flutter 3.16) following this change: https://github.com/bizz84/layout-demo-flutter/pull/16
