### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by ddean6232** [bizz84/layout-demo-flutter#6]
```Launching lib\main.dart on Pixel 2 XL in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not create service of type GeneralCompileCaches using GradleScopeCompileServices.createGeneralCompileCaches().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
BUILD FAILED in 31s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

Your code on 'layout-demo-flutter'  I have no idea where to start to resolve this... any thoughts??

**Comment by sahilpatel09** [comment]
I was having the same problem with gradle. So I tried a lot of option but at the end only one thing helped.

1. Run 'flutter clean'
2. Restart the pc

this worked for me. Hope it works for you

**Comment by bizz84** [comment]
@ddean6232 I updated the project. Can you see if it works now?

**Comment by souravroyrickey** [comment]
I am facing the same issue and tried flutter clean and restart pc. but it did not work.

**Comment by bizz84** [comment]
Recently updated the Android project.
