### ISSUE TITLE
Could not build the application for the simulator

### ISSUE THREAD

**Issue by adavis605** [bizz84/layout-demo-flutter#7]
Below is the error message I received trying to run the app on my ios simulator in android studio. I am new to coding dart and flutter. How do i get this to run? I would like to download this app to my phone also to study on the go. Please help with that also. Thanks in advance

Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                            1.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    diff: /Podfile.lock: No such file or directory
    diff: /Manifest.lock: No such file or directory
    error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

**Comment by yalva** [comment]
Had the same issue, as shown in he error, running the pod install under ios directory resolved it.

**Comment by bizz84** [comment]
@adavis605  I updated the project. Can you try again?

**Comment by Rakhimjon** [comment]
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    error: /Users/rahimjonabdullayev/AndroidStudioProjects/layout-demo-flutter/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')
    error: /Users/rahimjonabdullayev/AndroidStudioProjects/layout-demo-flutter/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')
    error: /Users/rahimjonabdullayev/AndroidStudioProjects/layout-demo-flutter/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')
    warning: The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target. (in target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 11.
I am update app no failed

**Comment by wxw-matt** [comment]
Just fixed this issue:
Please check out https://github.com/wxw-matt/layout-demo-flutter
Hope @bizz84 will merge this pull request.

**Comment by bizz84** [comment]
Should be fixed after #16.
