### ISSUE TITLE
hero_page.dart fails to run

### ISSUE THREAD

**Issue by PythonCodingUnicorn** [bizz84/layout-demo-flutter#8]
In Android Studio, running everything up to date.  Imported all dependencies upon cloning file.
The only file with errors that won't run.

console:
`Launching lib/main.dart on iPhone 11 Pro Max in debug mode...

Compiler message:
lib/pages/hero_page.dart:6:7: Error: The non-abstract class 'HeroHeader' is missing implementations for these members:
 - SliverPersistentHeaderDelegate.stretchConfiguration
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class HeroHeader implements SliverPersistentHeaderDelegate {
      ^^^^^^^^^^
../../Developer/flutter/packages/flutter/lib/src/widgets/sliver_persistent_header.dart:80:44: Context: 'SliverPersistentHeaderDelegate.stretchConfiguration' is defined here.
  OverScrollHeaderStretchConfiguration get stretchConfiguration => null;
                                           ^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11 Pro Max.`

**Comment by shortland** [comment]
Seems to be from changes to Flutters core. 
Not sure exactly how to fix it, but if you want it to work temporarily - you can remove `lib/pages/hero_page.dart` and comment out the usage of it in `lib/main_page.dart`.

Personally, I also had to migrate the project to AndroidX, and update the project's grade version.

```diff
diff --git a/lib/main_page.dart b/lib/main_page.dart
index 024bc28..89e455c 100644
--- a/lib/main_page.dart
+++ b/lib/main_page.dart
@@ -8,7 +8,7 @@ import 'package:layout_demo_flutter/pages/nested_page.dart';
 import 'package:layout_demo_flutter/pages/padding_page.dart';
 import 'package:layout_demo_flutter/pages/page_view_page.dart';
 import 'package:layout_demo_flutter/pages/row_column_page.dart';
-import 'package:layout_demo_flutter/pages/slivers_page.dart';
+// import 'package:layout_demo_flutter/pages/slivers_page.dart';
 import 'package:layout_demo_flutter/pages/stack_page.dart';
 
 class MainPage extends StatefulWidget {
@@ -93,10 +93,6 @@ class _MainPageState extends State<MainPage> {
           layoutGroup: _layoutGroup, onLayoutToggle: _onLayoutGroupToggle),
       LayoutType.list: (_) => ListPage(
           layoutGroup: _layoutGroup, onLayoutToggle: _onLayoutGroupToggle),
-      LayoutType.slivers: (_) => SliversPage(
-          layoutGroup: _layoutGroup, onLayoutToggle: _onLayoutGroupToggle),
-      LayoutType.hero: (_) => HeroPage(
-          layoutGroup: _layoutGroup, onLayoutToggle: _onLayoutGroupToggle),
       LayoutType.nested: (_) => NestedPage(
           layoutGroup: _layoutGroup, onLayoutToggle: _onLayoutGroupToggle),
     }[_layoutSelection](context);
```

**Comment by bizz84** [comment]
@PythonCodingUnicorn thanks for reporting. This is now fixed.
