### ISSUE TITLE
Error class HeroHeader

### ISSUE THREAD

**Issue by gogreen42** [bizz84/layout-demo-flutter#9]
Missing concrete implementation of 'getter SliverPersistentHeaderDelegate.stretchConfiguration'.
Try implementing the missing method, or make the class abstract.dart(non_abstract_class_inherits_abstract_member)

![error](https://user-images.githubusercontent.com/19793832/72428863-3e1e8b80-3797-11ea-9613-9e8ba58061be.PNG)

**Comment by veronesecoms** [comment]
facing the same problem, you fix this?

**Comment by oguzhanaltan** [comment]
in hero_page.dart
Find-->class HeroHeader implements SliverPersistentHeaderDelegate
Put "extends" instead "implements"

**Comment by bizz84** [comment]
I fixed this in the latest `master`
